meterdata:
  outputs:

    dev:
      type: trino
      method: none  # optional, one of {none | ldap | kerberos}
      user: trino
      password:   # required if method is ldap or kerberos
      database: iceberg
      host: localhost
      port: 8081
      schema: readings
      threads: 1

    prod:
      type: trino
      method: none  # optional, one of {none | ldap | kerberos}
      user: "{{ env_var('DBT_TRINO_USER', 'trino') }}"
      password: "{{ env_var('DBT_TRINO_PASSWORD', '') }}"
      database: "{{ env_var('DBT_TRINO_DATABASE', 'iceberg') }}"
      host: "{{ env_var('DBT_TRINO_HOST', 'trino') }}"
      port: "{{ env_var('DBT_TRINO_PORT', '8080') | int }}"
      schema: "{{ env_var('DBT_TRINO_SCHEMA', 'readings') }}"
      threads: "{{ env_var('DBT_THREADS', '1') | int }}"

  target: "{{ env_var('DBT_TARGET', 'dev') }}"
