version: 2

models:
  - name: readings__silver
    description: "Silver layer cleaned readings built from raw.readings with incremental processing and daily partitioning"
    config:
      materialized: incremental
      unique_key: id
      incremental_strategy: merge
    columns:
      - name: id
        description: "Unique identifier for each reading"
        data_tests:
          - unique
          - not_null
      - name: meter_id
        description: "Meter identifier"
        data_tests:
          - not_null
      - name: interval_start
        description: "Interval start timestamp"
        data_tests:
          - not_null
      - name: reading_value
        description: "Reading value"
        data_tests:
          - not_null
      - name: creation_time
        description: "Record creation timestamp used for incremental processing"
        data_tests:
          - not_null
      - name: creation_date
        description: "Date partition column derived from creation_time"
        data_tests:
          - not_null
