version: 2

models:
  - name: hub_customer
    description: "Hub containing unique customer business keys"
    columns:
      - name: customer_hk
        description: "Customer hash key"
        tests:
          - not_null
          - unique
      - name: customer_id
        description: "Customer business key (installation_id)"
        tests:
          - not_null
      - name: load_ts
        description: "Load timestamp"
        tests:
          - not_null
      - name: record_source
        description: "Source system identifier"
        tests:
          - not_null

  - name: hub_customer_account
    description: "Hub containing unique customer account business keys"
    columns:
      - name: customer_account_hk
        description: "Customer account hash key"
        tests:
          - not_null
          - unique
      - name: customer_account_id
        description: "Customer account business key (meter_id)"
        tests:
          - not_null
      - name: load_ts
        description: "Load timestamp"
        tests:
          - not_null
      - name: record_source
        description: "Source system identifier"
        tests:
          - not_null

  - name: hub_asset
    description: "Hub containing unique asset business keys"
    columns:
      - name: asset_hk
        description: "Asset hash key"
        tests:
          - not_null
          - unique
      - name: asset_id
        description: "Asset business key (meter_id)"
        tests:
          - not_null
      - name: load_ts
        description: "Load timestamp"
        tests:
          - not_null
      - name: record_source
        description: "Source system identifier"
        tests:
          - not_null
